language: python
python:
    - "3.5"
    - "3.6"
install:
    - pip install --upgrade pip
    - pip install coveralls coverage
    - pip install --upgrade -r requirements.txt
    - python setup.py install
script: coverage run setup.py test
after_success: coveralls
