"""create political parties table

Revision ID: 6721a0c04ae2
Revises: 
Create Date: 2017-08-22 13:32:47.256809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6721a0c04ae2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    parties_table = op.create_table('parties',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.bulk_insert(parties_table, [
        {"id": "C", "name": "Conservative Party"},
        {"id": "L", "name": "Labour Party"},
        {"id": "UKIP", "name": "UKIP"},
        {"id": "LD", "name": "Liberal Democrats"},
        {"id": "G", "name": "Green Party"},
        {"id": "Ind", "name": "Independent"},
        {"id": "SNP", "name": "SNP"},
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parties')
    # ### end Alembic commands ###
