"""add constituency and voting models

Revision ID: 92fd539a5ab0
Revises: 6721a0c04ae2
Create Date: 2017-08-22 16:40:51.294953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92fd539a5ab0'
down_revision = '6721a0c04ae2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('constituencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('votings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('constituency_id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['constituency_id'], ['constituencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votings')
    op.drop_table('constituencies')
    # ### end Alembic commands ###
